import { BarSpot } from "@/types/bar";

/** 横浜駅周辺を想定したモック座標 */
export const BAR_SPOTS: BarSpot[] = [
  {
    id: "b1",
    name: "Bar Lantern",
    area: "横浜西口",
    nearestStation: "横浜",
    walkMinutes: 4,
    priceRange: "mid",
    vibe: "casual",
    beginnerFriendly: true,
    soloFriendly: true,
    noCoverCharge: false,
    openUntil: "02:00",
    note: "カウンター中心で初来店が多い。会話もほどよい。",
    latitude: 35.4672,
    longitude: 139.6175,
  },
  {
    id: "b2",
    name: "Quiet Cask",
    area: "横浜東口",
    nearestStation: "横浜",
    walkMinutes: 8,
    priceRange: "high",
    vibe: "quiet",
    beginnerFriendly: false,
    soloFriendly: true,
    noCoverCharge: true,
    openUntil: "01:00",
    note: "静かに飲みたい方向け。ウイスキーが豊富。",
    latitude: 35.4648,
    longitude: 139.628,
  },
  {
    id: "b3",
    name: "Yoko Highball",
    area: "鶴屋町",
    nearestStation: "横浜",
    walkMinutes: 6,
    priceRange: "low",
    vibe: "lively",
    beginnerFriendly: true,
    soloFriendly: false,
    noCoverCharge: true,
    openUntil: "03:00",
    note: "立ち寄りやすい雰囲気。にぎやかめ。",
    latitude: 35.4645,
    longitude: 139.619,
  },
  {
    id: "b4",
    name: "Counter 23",
    area: "野毛",
    nearestStation: "桜木町",
    walkMinutes: 5,
    priceRange: "mid",
    vibe: "casual",
    beginnerFriendly: true,
    soloFriendly: true,
    noCoverCharge: true,
    openUntil: "24:00",
    note: "1人客比率が高く、スタッフが丁寧。",
    latitude: 35.4505,
    longitude: 139.6295,
  },
  {
    id: "b5",
    name: "Blue Velvet",
    area: "関内",
    nearestStation: "関内",
    walkMinutes: 3,
    priceRange: "high",
    vibe: "quiet",
    beginnerFriendly: false,
    soloFriendly: true,
    noCoverCharge: false,
    openUntil: "01:30",
    note: "落ち着いた接客。デート利用も多い。",
    latitude: 35.4428,
    longitude: 139.637,
  },
];
